from enum import IntEnum


class ErrorCode(IntEnum):
    TOKEN_NOT_PROVIDED = 1000
    INVALID_TOKEN_PROVIDED = 1001

    WRONG_PAGE_NUMBER_PROVIDED = 2000
    WRONG_PER_PAGE_NUMBER_PROVIDED = 2001

    USER_NOT_EXISTS = 3000

    COTE_NOT_EXISTS = 4000

    WRONG_OWNER_ID = 5000
